Create TestReportDetails.py
# Given the logs of  test execution create a report which has following parameter 

==============================================
Utility Tested: Usbtest
OS Arch: 64bit
OS Flavor: Windows 10
Product Version: 20.2.33
Total Tests Run: &lt;test count&gt;
Total Tests Failed: &lt;test fail count&gt;
Total Tests Passed: &lt;test pass count&gt;
Test Execution Time: total time taken for the suite to run
=====================================================


Test Run Beginning: 7/12/2021 12:08:35 PM Test Version: 2.1.0.0


7/12/2021 12:08:35 PM

Executing: C:\Program Files (x86)\tester\t_iclear.exe -a lan,5025[[fe80::5d0f:5100:7f81:9127]] -n 5 -S Test Passed!!!!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



7/12/2021 12:11:58 PM

Executing: C:\Program Files (x86)\tester\badbuf.exe -a lan,5025[[fe80::5d0f:5100:7f81:9127]] -S ERROR: id == 0: No connection
ERROR: Test stopped on Error

Test FAILED!!!!!!!!!!!!!!!!!!!!!!!!!!!

Failing Test: badbuf

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



7/12/2021 12:13:36 PM

Executing: C:\Program Files (x86)\tester\blk_num.exe -S Test Passed!!!!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



7/12/2021 12:14:04 PM

Executing: C:\Program Files (x86)\tester\badid.exe -a lan,5025[[fe80::5d0f:5100:7f81:9127]] -S ERROR: id == 0: No connection
ERROR: Test stopped on Error

Test FAILED!!!!!!!!!!!!!!!!!!!!!!!!!!!

Failing Test: badid ###############################################################
Test Run Ended: 7/12/2021 12:15:04 PM